pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo "Running build step..."
                sh 'echo "Pretend build commands"'
            }
        }
        stage('Build') {
            steps {
                echo "Running build step..."
                sh 'echo "Pretend build commands"'
            }
        }
        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'echo "Pretend test commands"'
            }
        }
    }
}
