pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'test_jenkins', url: 'https://github.com/cidinhadevplace/jenkins_ansible.git'
            }
        }
        stage('Build') {
            steps {
                echo "Running build step..."
                sh 'echo "Pretend build commands"'
            }
        }
        stage('Build') {
            steps {
                echo "Running build step..."
                sh 'echo "Pretend build commands"'
            }
        }
        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'echo "Pretend test commands"'
            }
        }
    }
}
